FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# API example
Backup: https://github.com/Hubackova/api-example
## Whole Table [/table]

### List All Table Cells [GET]

+ Response 200 (application/json)

        [
          {
            "stepIndex": 1,
            "stepDuration": 10,
            "perimeter1": {
              "OUT": "IN1"
            },
            "perimeter2": {
              "OUT": "IN1"
            },
            "perimeter3": {
              "OUT": "IN1"
            },
            "perimeter4": {
              "OUT": "IN1"
            },
            "perimeter5": {
              "OUT": "IN1"
            },
            "perimeter5": {
              "OUT": "IN1"
            },
            "perimeter6": {
              "OUT": "IN1"
            },
            "perimeter7": {
              "OUT": "IN1"
            },
            "perimeter8": {
              "OUT": "IN1"
            },
            "perimeter9": {
              "OUT": "IN1"
            },
            "perimeter10": {
              "OUT": "IN1"
            },
            "perimeter11": {
              "OUT": "IN1"
            },
            "perimeter12": {
              "OUT": "IN1"
            },
            "perimeter13": {
              "OUT": "IN1"
            },
            "perimeter14": {
              "OUT": "IN1"
            },
            "perimeter15": {
              "OUT": "IN1"
            },
            "perimeter16": {
              "OUT": "IN1"
            },
            "inner1": {
              "OUT": "IN3"
            },
            "inner2": {
              "OUT": "IN7"
            },
            "inner3": {
              "OUTA": "IN1A",
              "OUTB": "IN3B"
            },
            "inner4": {
              "OUT": 5
            },
            "inner5": {
              "OUTA": 5,
              "OUTB": 7
            },
            "inner6": {
              "OUT": "ON"
            },
            "inner7": {
              "OUTA": "ON",
              "OUTB": "OFF"
            }
          },
          {
            "stepIndex": 2,
            "stepDuration": 15,
            "perimeter1": {
              "OUT": "IN1"
            },
            "perimeter2": {
              "OUT": "IN2-AMP"
            },
            "perimeter3": {
              "OUT": "BP"
            },
            "perimeter4": {
              "OUTA": "IN1-AMP",
              "OUTB": "IN2-BP"
            },
            "perimeter5": {
              "OUTA": "ON",
              "OUTB": "OFF"
            },
            "inner1": {
              "OUT": "IN3"
            },
            "inner2": {
              "OUT": "IN7"
            },
            "inner3": {
              "OUTA": "IN1A",
              "OUTB": "IN3B"
            },
            "inner4": {
              "OUT": 5
            },
            "inner5": {
              "OUTA": 5,
              "OUTB": 7
            },
            "inner6": {
              "OUT": "ON"
            },
            "inner7": {
              "OUTA": "ON",
              "OUTB": "OFF"
            }
          }
        ]



## Module values [/module-values]

### List All Module options values [GET]

+ Response 200 (application/json)

        {
            "RxSP4T":{
                "OUT":[
                    "IN1",
                    "IN2",
                    "IN3",
                    "IN4"
                ]
            },
            "RxSPDT":{
                "OUT":[
                    "IN1-AMP",
                    "IN-1BP",
                    "IN2-AMP",
                    "IN2-BP"
                ]
            },
            "RxSPDTDual":{
                "OUTA":[
                    "IN1-AMP",
                    "IN1-BP",
                    "IN2-AMP",
                    "IN2-BP"
                ],
                "OUTB":[
                    "IN1-AMP",
                    "IN1-BP",
                    "IN2-AMP",
                    "IN2-BP"
                ]
            },
            "RxSingle":{
                "OUT":[
                    "AMP",
                    "BP"
                ]
            },
            "RxSingleDual":{
                "OUTA":[
                    "ON",
                    "OFF"
                ],
                "OUTB":[
                    "ON",
                    "OFF"
                ]
            },
            "SwitchSP4T":{
                "OUT":[
                    "IN1",
                    "IN2",
                    "IN3",
                    "IN4"
                ]
            },
            "SwitchSP8T":{
                "OUT":[
                    "IN1",
                    "IN2",
                    "IN3",
                    "IN4",
                    "IN5",
                    "IN6",
                    "IN7",
                    "IN8"
                ]
            },
            "NoiceSource":{
                "OUT":[
                    "ON",
                    "OFF"
                ]
            },
            "SwitchDP4T":{
                "OUTA":[
                    "IN1A",
                    "IN2A",
                    "IN3A",
                    "IN4A"
                ],
                "OUTB":[
                    "IN1B",
                    "IN2B",
                    "IN3B",
                    "IN4B"
                ]
            },
            "Attenuator":{
                "OUT":{
                    "min":0,
                    "max":7,
                    "step":1,
                    "unit":"dB"
                }
            },
            "AttenuatorDual":{
                "OUTA":{
                    "min":0,
                    "max":7,
                    "step":1,
                    "unit":"dB"
                },
                "OUTB":{
                    "min":0,
                    "max":7,
                    "step":1,
                    "unit":"dB"
                }
            },
            "Amplifier":{
                "OUT":[
                    "ON",
                    "OFF"
                ]
            },
            "AmplifierDual":{
                "OUTA":[
                    "ON",
                    "OFF"
                ],
                "OUTB":[
                    "ON",
                    "OFF"
                ]
            }
        }
        
## Table headers [/table-headers]
### Get  [GET]

+ Response 200 (application/json)

        {
          "stepIndex": {
            "key": "stepIndex",
            "headerLabel": "Step Index"
          },
          "stepDuration": {
            "key": "stepDuration",
            "headerLabel": "Step Duration"
          },
          "perimeter1": {
            "key": "perimeter1",
            "headerLabel": "Perimeter 1",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter2": {
            "key": "perimeter2",
            "headerLabel": "Perimeter 2",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter3": {
            "key": "perimeter3",
            "headerLabel": "Perimeter 3",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter4": {
            "key": "perimeter4",
            "headerLabel": "Perimeter 4",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter5": {
            "key": "perimeter5",
            "headerLabel": "Perimeter 5",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter6": {
            "key": "perimeter6",
            "headerLabel": "Perimeter 6",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter7": {
            "key": "perimeter7",
            "headerLabel": "Perimeter 7",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter8": {
            "key": "perimeter8",
            "headerLabel": "Perimeter 8",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter9": {
            "key": "perimeter9",
            "headerLabel": "Perimeter 9",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter10": {
            "key": "perimeter10",
            "headerLabel": "Perimeter 10",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter11": {
            "key": "perimeter11",
            "headerLabel": "Perimeter 11",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter12": {
            "key": "perimeter12",
            "headerLabel": "Perimeter 12",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter13": {
            "key": "perimeter13",
            "headerLabel": "Perimeter 13",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter14": {
            "key": "perimeter14",
            "headerLabel": "Perimeter 14",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter15": {
            "key": "perimeter15",
            "headerLabel": "Perimeter 15",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "perimeter16": {
            "key": "perimeter16",
            "headerLabel": "Perimeter 16",
            "idPlug": "RxSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "inner1": {
            "key": "inner1",
            "headerLabel": "Inner 1",
            "idPlug": "SwitchSP4T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "inner2": {
            "key": "inner2",
            "headerLabel": "Inner 2",
            "idPlug": "SwitchSP8T",
            "outputs": {
              "OUT": "OUT"
            }
          },
          "inner3": {
            "key": "inner3",
            "headerLabel": "Inner 3",
            "idPlug": "SwitchDP4T",
            "outputs": {
              "OUTA": "OUTA",
              "OUTB": "OUTB"
            }
          },
          "inner4": {
            "key": "inner4",
            "headerLabel": "Inner 4",
            "idPlug": "Attenuator",
            "outputs": {
              "OUT": "ATTN"
            }
          },
          "inner5": {
            "key": "inner5",
            "headerLabel": "Inner 5",
            "idPlug": "AttenuatorDual",
            "outputs": {
              "OUTA": "ATTNA",
              "OUTB": "ATTNB"
            }
          },
          "inner6": {
            "key": "inner6",
            "headerLabel": "Inner 6",
            "idPlug": "Amplifier",
            "outputs": {
              "OUT": "AMP"
            }
          },
          "inner7": {
            "key": "inner7",
            "headerLabel": "Inner 7",
            "idPlug": "AmplifierDual",
            "outputs": {
              "OUTA": "AMPA",
              "OUTB": "AMPB"
            }
          }
        }

        
## Table update [/table/{time}]
### Update time-values in a column [PUT]
Update tabulky 
in progress - podle toho, jak se domluvime na GET tabulky 

+ Request (application/json)

+ Attributes

            
+ Parameters
    + time (integer) - ID radku (casu) jako integer       

+ Response 200 (application/json)